= Gridsolve

A program for solving grid logic puzzles while printing out its reasoning.

== Getting Started

See the link:./puzzles/[puzzles] directory for the puzzle format.

== Inspiration

The program is based on Escamocher and O'Sullivan's paper
https://arxiv.org/pdf/1910.06636.pdf[Solving Logic Grid Puzzles with an Algorithm that Imitates Human Behavior], with some modifications.

== Example

Here's the output when solving the example provided in the paper:

* The person from the “United States” was born in “1946”.
* “Leo” is younger than the person from “Germany”.
* “Donald” was born in “1946”, or he is from “Ireland”.

Running `./gridsolve -v puzzles/simple.txt`:
....
Running constraints...
  United States | 1946 => Yes
  Leo | Germany => No
  Leo | 1946 => No
  Germany | 1979 => No
Running ElimOthers...
  United States | 1954 => No
  United States | 1979 => No
  Germany | 1946 => No
  Ireland | 1946 => No
Running OnlyEmpty...
  Germany | 1954 => Yes
  Ireland | 1979 => Yes
Running Transitivity...
Running NoByProxy...
  Leo | United States => No
Running constraints...
  Leo | 1954 => No
  Germany | Donald => No
Running ElimOthers...
  Ireland | 1954 => No
Running OnlyEmpty...
  Angela | Germany => Yes
  Leo | Ireland => Yes
  Leo | 1979 => Yes
Running Transitivity...
  Angela | 1954 => Yes
Running NoByProxy...
  Donald | 1954 => No
Running constraints...
Running ElimOthers...
  Angela | Ireland => No
  Angela | United States => No
  Angela | 1946 => No
  Angela | 1979 => No
  Donald | Ireland => No
  Donald | 1979 => No
Running OnlyEmpty...
  Donald | United States => Yes
  Donald | 1946 => Yes
Running Transitivity...
Running NoByProxy...
Running constraints...
Running ElimOthers...
Running OnlyEmpty...
Running Transitivity...
Running NoByProxy...
+------------+---------------+---------------+
| First Name | Country       | Year of Birth |
+------------+---------------+---------------+
| Angela     | Germany       | 1954          |
+------------+---------------+---------------+
| Donald     | United States | 1946          |
+------------+---------------+---------------+
| Leo        | Ireland       | 1979          |
+------------+---------------+---------------+
....
