= Gridsolve

A program for solving grid logic puzzles while printing out its reasoning.

== Getting Started

Try it out on the https://avp.github.io/gridsolve[website] for a simple input format.

Example puzzle can be found https://avp.github.io/gridsolve/#%7B%22categories%22%3A%5B%22name%22%2C%22country%22%2C%22year%22%5D%2C%22labels%22%3A%5B%22angela%22%2C%22donald%22%2C%22leo%22%2C%22germany%22%2C%22ireland%22%2C%22usa%22%2C%221946%22%2C%221954%22%2C%221979%22%5D%2C%22numLabels%22%3A%223%22%2C%22clues%22%3A%5B%7B%22name%22%3A%221%22%2C%22kind%22%3A%22yes%22%2C%22params%22%3A%5B%225%22%2C%226%22%5D%7D%2C%7B%22name%22%3A%222%22%2C%22kind%22%3A%22after%22%2C%22params%22%3A%5B%222%22%2C%222%22%2C%223%22%5D%7D%2C%7B%22name%22%3A%223%22%2C%22kind%22%3A%22or%22%2C%22params%22%3A%5B%221%22%2C%226%22%2C%224%22%5D%7D%5D%7D[here] if you don't have one of your own.

Or use the CLI program with `cargo run`,
and see the link:./puzzles/[puzzles] directory for the puzzle format.

== Inspiration

The program is based on Escamocher and O'Sullivan's paper
https://arxiv.org/pdf/1910.06636.pdf[Solving Logic Grid Puzzles with an Algorithm that Imitates Human Behavior], with some modifications.

== Example

Here's the output when solving the example provided in the paper:

* The person from the “United States” was born in “1946”.
* “Leo” is younger than the person from “Germany”.
* “Donald” was born in “1946”, or he is from “Ireland”.

Running `./gridsolve -v puzzles/simple.txt`:
....
Running constraints...
  United States | 1946 => Yes
  Leo | Germany => No
  Leo | 1946 => No
  Germany | 1979 => No
Running ElimOthers...
  United States | 1954 => No
  United States | 1979 => No
  Germany | 1946 => No
  Ireland | 1946 => No
Running OnlyEmpty...
  Germany | 1954 => Yes
  Ireland | 1979 => Yes
Running Transitivity...
Running NoByProxy...
  Leo | United States => No
Running constraints...
  Leo | 1954 => No
  Germany | Donald => No
Running ElimOthers...
  Ireland | 1954 => No
Running OnlyEmpty...
  Angela | Germany => Yes
  Leo | Ireland => Yes
  Leo | 1979 => Yes
Running Transitivity...
  Angela | 1954 => Yes
Running NoByProxy...
  Donald | 1954 => No
Running constraints...
Running ElimOthers...
  Angela | Ireland => No
  Angela | United States => No
  Angela | 1946 => No
  Angela | 1979 => No
  Donald | Ireland => No
  Donald | 1979 => No
Running OnlyEmpty...
  Donald | United States => Yes
  Donald | 1946 => Yes
Running Transitivity...
Running NoByProxy...
Running constraints...
Running ElimOthers...
Running OnlyEmpty...
Running Transitivity...
Running NoByProxy...
+------------+---------------+---------------+
| First Name | Country       | Year of Birth |
+------------+---------------+---------------+
| Angela     | Germany       | 1954          |
+------------+---------------+---------------+
| Donald     | United States | 1946          |
+------------+---------------+---------------+
| Leo        | Ireland       | 1979          |
+------------+---------------+---------------+
....

