name: Build and deploy website

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jetli/wasm-pack-action@v0.3.0
    - uses: actions/setup-node@v2
    - uses: actions/checkout@v3
    - name: download esbuild
      run: npm install -g esbuild
    - name: install deps
      run: |
        cd www
        npm install
    - name: build
      run: make release
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
